version: '3'
services:
  db:
    image: mongo
    environment:
      - MONGODB_USER=complaint
      - MONGODB_PASS=complaint
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - .mongo:/data/db
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
      - .bundle:/usr/local/bundle
    ports:
      - 3000:3000
    depends_on:
      - db
