version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=complaint
      - POSTGRES_PASSWORD=complaint
    volumes:
      - .postgresql:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
      - .bundle:/usr/local/bundle
    ports:
      - 3000:3000
    depends_on:
      - db
